version: "3.2"

services:
  registry:
    container_name: registry
    image: registry:2.6
    restart: always
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/app/auth/htpasswd
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/registry
      - type: bind
        source: ./auth
        target: /app/auth
  registry-ui:
    image: joxit/docker-registry-ui:1.4-static
    depends_on:
      - registry
    restart: always
    ports:
      - "5080:80"
    environment:
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Private registry
